default: &default
  thumbnail_width: 200
  api_url: 'http://demo.pixomatix.com/api' # URL to Pixomatix-Api
  api_version: 'v1'

development:
  <<: *default
  api_url: 'http://localhost:1234/api'
  api_version: 'v1'

test:
  <<: *default
  api_url: '/api'
  api_version: 'v1'

stage:
  <<: *default
  api_url: '/api'
  api_version: 'v1'

production:
  <<: *default
  api_url: '/api'
  api_version: 'v1'
